using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nulah.PhantomIndex.Core.Controls
{
    internal static class SegoeMDL2AssetsFontIcons
    {
        private static Dictionary<string, string> _icons = new Dictionary<string, string> {
            { "GlobalNavigationButton", "\xE700" },
            { "Wifi", "\xE701" },
            { "Bluetooth", "\xE702" },
            { "Connect", "\xE703" },
            { "InternetSharing", "\xE704" },
            { "VPN", "\xE705" },
            { "Brightness", "\xE706" },
            { "MapPin", "\xE707" },
            { "QuietHours", "\xE708" },
            { "Airplane", "\xE709" },
            { "Tablet", "\xE70A" },
            { "QuickNote", "\xE70B" },
            { "RememberedDevice", "\xE70C" },
            { "ChevronDown", "\xE70D" },
            { "ChevronUp", "\xE70E" },
            { "Edit", "\xE70F" },
            { "Add", "\xE710" },
            { "Cancel", "\xE711" },
            { "More", "\xE712" },
            { "Setting", "\xE713" },
            { "Video", "\xE714" },
            { "Mail", "\xE715" },
            { "People", "\xE716" },
            { "Phone", "\xE717" },
            { "Pin", "\xE718" },
            { "Shop", "\xE719" },
            { "Stop", "\xE71A" },
            { "Link", "\xE71B" },
            { "Filter", "\xE71C" },
            { "AllApps", "\xE71D" },
            { "Zoom", "\xE71E" },
            { "ZoomOut", "\xE71F" },
            { "Microphone", "\xE720" },
            { "Search", "\xE721" },
            { "Camera", "\xE722" },
            { "Attach", "\xE723" },
            { "Send", "\xE724" },
            { "SendFill", "\xE725" },
            { "WalkSolid", "\xE726" },
            { "InPrivate", "\xE727" },
            { "FavoriteList", "\xE728" },
            { "PageSolid", "\xE729" },
            { "Forward", "\xE72A" },
            { "Back", "\xE72B" },
            { "Refresh", "\xE72C" },
            { "Share", "\xE72D" },
            { "Lock", "\xE72E" },
            { "ReportHacked", "\xE730" },
            { "EMI", "\xE731" },
            { "FavoriteStar", "\xE734" },
            { "FavoriteStarFill", "\xE735" },
            { "ReadingMode", "\xE736" },
            { "Favicon", "\xE737" },
            { "Remove", "\xE738" },
            { "Checkbox", "\xE739" },
            { "CheckboxComposite", "\xE73A" },
            { "CheckboxFill", "\xE73B" },
            { "CheckboxIndeterminate", "\xE73C" },
            { "CheckboxCompositeReversed", "\xE73D" },
            { "CheckMark", "\xE73E" },
            { "BackToWindow", "\xE73F" },
            { "FullScreen", "\xE740" },
            { "ResizeTouchLarger", "\xE741" },
            { "ResizeTouchSmaller", "\xE742" },
            { "ResizeMouseSmall", "\xE743" },
            { "ResizeMouseMedium", "\xE744" },
            { "ResizeMouseWide", "\xE745" },
            { "ResizeMouseTall", "\xE746" },
            { "ResizeMouseLarge", "\xE747" },
            { "SwitchUser", "\xE748" },
            { "Print", "\xE749" },
            { "Up", "\xE74A" },
            { "Down", "\xE74B" },
            { "OEM", "\xE74C" },
            { "Delete", "\xE74D" },
            { "Save", "\xE74E" },
            { "Mute", "\xE74F" },
            { "BackSpaceQWERTY", "\xE750" },
            { "ReturnKey", "\xE751" },
            { "UpArrowShiftKey", "\xE752" },
            { "Cloud", "\xE753" },
            { "Flashlight", "\xE754" },
            { "RotationLock", "\xE755" },
            { "CommandPrompt", "\xE756" },
            { "SIPMove", "\xE759" },
            { "SIPUndock", "\xE75A" },
            { "SIPRedock", "\xE75B" },
            { "EraseTool", "\xE75C" },
            { "UnderscoreSpace", "\xE75D" },
            { "GripperTool", "\xE75E" },
            { "Dialpad", "\xE75F" },
            { "PageLeft", "\xE760" },
            { "PageRight", "\xE761" },
            { "MultiSelect", "\xE762" },
            { "KeyboardLeftHanded", "\xE763" },
            { "KeyboardRightHanded", "\xE764" },
            { "KeyboardClassic", "\xE765" },
            { "KeyboardSplit", "\xE766" },
            { "Volume", "\xE767" },
            { "Play", "\xE768" },
            { "Pause", "\xE769" },
            { "ChevronLeft", "\xE76B" },
            { "ChevronRight", "\xE76C" },
            { "InkingTool", "\xE76D" },
            { "Emoji2", "\xE76E" },
            { "GripperBarHorizontal", "\xE76F" },
            { "System", "\xE770" },
            { "Personalize", "\xE771" },
            { "Devices", "\xE772" },
            { "SearchAndApps", "\xE773" },
            { "Globe", "\xE774" },
            { "TimeLanguage", "\xE775" },
            { "EaseOfAccess", "\xE776" },
            { "UpdateRestore", "\xE777" },
            { "HangUp", "\xE778" },
            { "ContactInfo", "\xE779" },
            { "Unpin", "\xE77A" },
            { "Contact", "\xE77B" },
            { "Memo", "\xE77C" },
            { "IncomingCall", "\xE77E" },
            { "Paste", "\xE77F" },
            { "PhoneBook", "\xE780" },
            { "LEDLight", "\xE781" },
            { "Error", "\xE783" },
            { "GripperBarVertical", "\xE784" },
            { "Unlock", "\xE785" },
            { "Slideshow", "\xE786" },
            { "Calendar", "\xE787" },
            { "GripperResize", "\xE788" },
            { "Megaphone", "\xE789" },
            { "Trim", "\xE78A" },
            { "NewWindow", "\xE78B" },
            { "SaveLocal", "\xE78C" },
            { "Color", "\xE790" },
            { "DataSense", "\xE791" },
            { "SaveAs", "\xE792" },
            { "Light", "\xE793" },
            { "AspectRatio", "\xE799" },
            { "DataSenseBar", "\xE7A5" },
            { "Redo", "\xE7A6" },
            { "Undo", "\xE7A7" },
            { "Crop", "\xE7A8" },
            { "OpenWith", "\xE7AC" },
            { "Rotate", "\xE7AD" },
            { "RedEye", "\xE7B3" },
            { "SetlockScreen", "\xE7B5" },
            { "MapPin2", "\xE7B7" },
            { "Package", "\xE7B8" },
            { "Warning", "\xE7BA" },
            { "ReadingList", "\xE7BC" },
            { "Education", "\xE7BE" },
            { "ShoppingCart", "\xE7BF" },
            { "Train", "\xE7C0" },
            { "Flag", "\xE7C1" },
            { "Page", "\xE7C3" },
            { "TaskView", "\xE7C4" },
            { "BrowsePhotos", "\xE7C5" },
            { "HalfStarLeft", "\xE7C6" },
            { "HalfStarRight", "\xE7C7" },
            { "Record", "\xE7C8" },
            { "TouchPointer", "\xE7C9" },
            { "LangJPN", "\xE7DE" },
            { "Ferry", "\xE7E3" },
            { "Highlight", "\xE7E6" },
            { "ActionCenterNotification", "\xE7E7" },
            { "PowerButton", "\xE7E8" },
            { "ResizeTouchNarrower", "\xE7EA" },
            { "ResizeTouchShorter", "\xE7EB" },
            { "DrivingMode", "\xE7EC" },
            { "RingerSilent", "\xE7ED" },
            { "OtherUser", "\xE7EE" },
            { "Admin", "\xE7EF" },
            { "CC", "\xE7F0" },
            { "SDCard", "\xE7F1" },
            { "CallForwarding", "\xE7F2" },
            { "SettingsDisplaySound", "\xE7F3" },
            { "TVMonitor", "\xE7F4" },
            { "Speakers", "\xE7F5" },
            { "Headphone", "\xE7F6" },
            { "DeviceLaptopPic", "\xE7F7" },
            { "DeviceLaptopNoPic", "\xE7F8" },
            { "DeviceMonitorRightPic", "\xE7F9" },
            { "DeviceMonitorLeftPic", "\xE7FA" },
            { "DeviceMonitorNoPic", "\xE7FB" },
            { "Game", "\xE7FC" },
            { "HorizontalTabKey", "\xE7FD" },
            { "StreetsideSplitMinimize", "\xE802" },
            { "StreetsideSplitExpand", "\xE803" },
            { "Car", "\xE804" },
            { "Walk", "\xE805" },
            { "Bus", "\xE806" },
            { "TiltUp", "\xE809" },
            { "TiltDown", "\xE80A" },
            { "CallControl", "\xE80B" },
            { "RotateMapRight", "\xE80C" },
            { "RotateMapLeft", "\xE80D" },
            { "Home", "\xE80F" },
            { "ParkingLocation", "\xE811" },
            { "MapCompassTop", "\xE812" },
            { "MapCompassBottom", "\xE813" },
            { "IncidentTriangle", "\xE814" },
            { "Touch", "\xE815" },
            { "MapDirections", "\xE816" },
            { "StartPoint", "\xE819" },
            { "StopPoint", "\xE81A" },
            { "EndPoint", "\xE81B" },
            { "History", "\xE81C" },
            { "Location", "\xE81D" },
            { "MapLayers", "\xE81E" },
            { "Accident", "\xE81F" },
            { "Work", "\xE821" },
            { "Construction", "\xE822" },
            { "Recent", "\xE823" },
            { "Bank", "\xE825" },
            { "DownloadMap", "\xE826" },
            { "InkingToolFill2", "\xE829" },
            { "HighlightFill2", "\xE82A" },
            { "EraseToolFill", "\xE82B" },
            { "EraseToolFill2", "\xE82C" },
            { "Dictionary", "\xE82D" },
            { "DictionaryAdd", "\xE82E" },
            { "ToolTip", "\xE82F" },
            { "ChromeBack", "\xE830" },
            { "ProvisioningPackage", "\xE835" },
            { "AddRemoteDevice", "\xE836" },
            { "FolderOpen", "\xE838" },
            { "Ethernet", "\xE839" },
            { "ShareBroadband", "\xE83A" },
            { "DirectAccess", "\xE83B" },
            { "DialUp", "\xE83C" },
            { "DefenderApp", "\xE83D" },
            { "BatteryCharging9", "\xE83E" },
            { "Battery10", "\xE83F" },
            { "Pinned", "\xE840" },
            { "PinFill", "\xE841" },
            { "PinnedFill", "\xE842" },
            { "PeriodKey", "\xE843" },
            { "PuncKey", "\xE844" },
            { "RevToggleKey", "\xE845" },
            { "RightArrowKeyTime1", "\xE846" },
            { "RightArrowKeyTime2", "\xE847" },
            { "LeftQuote", "\xE848" },
            { "RightQuote", "\xE849" },
            { "DownShiftKey", "\xE84A" },
            { "UpShiftKey", "\xE84B" },
            { "PuncKey0", "\xE84C" },
            { "PuncKeyLeftBottom", "\xE84D" },
            { "RightArrowKeyTime3", "\xE84E" },
            { "RightArrowKeyTime4", "\xE84F" },
            { "Battery0", "\xE850" },
            { "Battery1", "\xE851" },
            { "Battery2", "\xE852" },
            { "Battery3", "\xE853" },
            { "Battery4", "\xE854" },
            { "Battery5", "\xE855" },
            { "Battery6", "\xE856" },
            { "Battery7", "\xE857" },
            { "Battery8", "\xE858" },
            { "Battery9", "\xE859" },
            { "BatteryCharging0", "\xE85A" },
            { "BatteryCharging1", "\xE85B" },
            { "BatteryCharging2", "\xE85C" },
            { "BatteryCharging3", "\xE85D" },
            { "BatteryCharging4", "\xE85E" },
            { "BatteryCharging5", "\xE85F" },
            { "BatteryCharging6", "\xE860" },
            { "BatteryCharging7", "\xE861" },
            { "BatteryCharging8", "\xE862" },
            { "BatterySaver0", "\xE863" },
            { "BatterySaver1", "\xE864" },
            { "BatterySaver2", "\xE865" },
            { "BatterySaver3", "\xE866" },
            { "BatterySaver4", "\xE867" },
            { "BatterySaver5", "\xE868" },
            { "BatterySaver6", "\xE869" },
            { "BatterySaver7", "\xE86A" },
            { "BatterySaver8", "\xE86B" },
            { "SignalBars1", "\xE86C" },
            { "SignalBars2", "\xE86D" },
            { "SignalBars3", "\xE86E" },
            { "SignalBars4", "\xE86F" },
            { "SignalBars5", "\xE870" },
            { "SignalNotConnected", "\xE871" },
            { "Wifi1", "\xE872" },
            { "Wifi2", "\xE873" },
            { "Wifi3", "\xE874" },
            { "MobSIMLock", "\xE875" },
            { "MobSIMMissing", "\xE876" },
            { "Vibrate", "\xE877" },
            { "RoamingInternational", "\xE878" },
            { "RoamingDomestic", "\xE879" },
            { "CallForwardInternational", "\xE87A" },
            { "CallForwardRoaming", "\xE87B" },
            { "JpnRomanji", "\xE87C" },
            { "JpnRomanjiLock", "\xE87D" },
            { "JpnRomanjiShift", "\xE87E" },
            { "JpnRomanjiShiftLock", "\xE87F" },
            { "StatusDataTransfer", "\xE880" },
            { "StatusDataTransferVPN", "\xE881" },
            { "StatusDualSIM2", "\xE882" },
            { "StatusDualSIM2VPN", "\xE883" },
            { "StatusDualSIM1", "\xE884" },
            { "StatusDualSIM1VPN", "\xE885" },
            { "StatusSGLTE", "\xE886" },
            { "StatusSGLTECell", "\xE887" },
            { "StatusSGLTEDataVPN", "\xE888" },
            { "StatusVPN", "\xE889" },
            { "WifiHotspot", "\xE88A" },
            { "LanguageKor", "\xE88B" },
            { "LanguageCht", "\xE88C" },
            { "LanguageChs", "\xE88D" },
            { "USB", "\xE88E" },
            { "InkingToolFill", "\xE88F" },
            { "View", "\xE890" },
            { "HighlightFill", "\xE891" },
            { "Previous", "\xE892" },
            { "Next", "\xE893" },
            { "Clear", "\xE894" },
            { "Sync", "\xE895" },
            { "Download", "\xE896" },
            { "Help", "\xE897" },
            { "Upload", "\xE898" },
            { "Emoji", "\xE899" },
            { "TwoPage", "\xE89A" },
            { "LeaveChat", "\xE89B" },
            { "MailForward", "\xE89C" },
            { "RotateCamera", "\xE89E" },
            { "ClosePane", "\xE89F" },
            { "OpenPane", "\xE8A0" },
            { "PreviewLink", "\xE8A1" },
            { "AttachCamera", "\xE8A2" },
            { "ZoomIn", "\xE8A3" },
            { "Bookmarks", "\xE8A4" },
            { "Document", "\xE8A5" },
            { "ProtectedDocument", "\xE8A6" },
            { "OpenInNewWindow", "\xE8A7" },
            { "MailFill", "\xE8A8" },
            { "ViewAll", "\xE8A9" },
            { "VideoChat", "\xE8AA" },
            { "Switch", "\xE8AB" },
            { "Rename", "\xE8AC" },
            { "Go", "\xE8AD" },
            { "SurfaceHub", "\xE8AE" },
            { "Remote", "\xE8AF" },
            { "Click", "\xE8B0" },
            { "Shuffle", "\xE8B1" },
            { "Movies", "\xE8B2" },
            { "SelectAll", "\xE8B3" },
            { "Orientation", "\xE8B4" },
            { "Import", "\xE8B5" },
            { "ImportAll", "\xE8B6" },
            { "Folder", "\xE8B7" },
            { "Webcam", "\xE8B8" },
            { "Picture", "\xE8B9" },
            { "Caption", "\xE8BA" },
            { "ChromeClose", "\xE8BB" },
            { "ShowResults", "\xE8BC" },
            { "Message", "\xE8BD" },
            { "Leaf", "\xE8BE" },
            { "CalendarDay", "\xE8BF" },
            { "CalendarWeek", "\xE8C0" },
            { "Characters", "\xE8C1" },
            { "MailReplyAll", "\xE8C2" },
            { "Read", "\xE8C3" },
            { "ShowBcc", "\xE8C4" },
            { "HideBcc", "\xE8C5" },
            { "Cut", "\xE8C6" },
            { "PaymentCard", "\xE8C7" },
            { "Copy", "\xE8C8" },
            { "Important", "\xE8C9" },
            { "MailReply", "\xE8CA" },
            { "Sort", "\xE8CB" },
            { "MobileTablet", "\xE8CC" },
            { "DisconnectDrive", "\xE8CD" },
            { "MapDrive", "\xE8CE" },
            { "ContactPresence", "\xE8CF" },
            { "Priority", "\xE8D0" },
            { "GotoToday", "\xE8D1" },
            { "Font", "\xE8D2" },
            { "FontColor", "\xE8D3" },
            { "Contact2", "\xE8D4" },
            { "FolderFill", "\xE8D5" },
            { "Audio", "\xE8D6" },
            { "Permissions", "\xE8D7" },
            { "DisableUpdates", "\xE8D8" },
            { "Unfavorite", "\xE8D9" },
            { "OpenLocal", "\xE8DA" },
            { "Italic", "\xE8DB" },
            { "Underline", "\xE8DC" },
            { "Bold", "\xE8DD" },
            { "MoveToFolder", "\xE8DE" },
            { "LikeDislike", "\xE8DF" },
            { "Dislike", "\xE8E0" },
            { "Like", "\xE8E1" },
            { "AlignRight", "\xE8E2" },
            { "AlignCenter", "\xE8E3" },
            { "AlignLeft", "\xE8E4" },
            { "OpenFile", "\xE8E5" },
            { "ClearSelection", "\xE8E6" },
            { "FontDecrease", "\xE8E7" },
            { "FontIncrease", "\xE8E8" },
            { "FontSize", "\xE8E9" },
            { "CellPhone", "\xE8EA" },
            { "Reshare", "\xE8EB" },
            { "Tag", "\xE8EC" },
            { "RepeatOne", "\xE8ED" },
            { "RepeatAll", "\xE8EE" },
            { "Calculator", "\xE8EF" },
            { "Directions", "\xE8F0" },
            { "Library", "\xE8F1" },
            { "ChatBubbles", "\xE8F2" },
            { "PostUpdate", "\xE8F3" },
            { "NewFolder", "\xE8F4" },
            { "CalendarReply", "\xE8F5" },
            { "UnsyncFolder", "\xE8F6" },
            { "SyncFolder", "\xE8F7" },
            { "BlockContact", "\xE8F8" },
            { "SwitchApps", "\xE8F9" },
            { "AddFriend", "\xE8FA" },
            { "Accept", "\xE8FB" },
            { "GoToStart", "\xE8FC" },
            { "BulletedList", "\xE8FD" },
            { "Scan", "\xE8FE" },
            { "Preview", "\xE8FF" },
            { "Group", "\xE902" },
            { "ZeroBars", "\xE904" },
            { "OneBar", "\xE905" },
            { "TwoBars", "\xE906" },
            { "ThreeBars", "\xE907" },
            { "FourBars", "\xE908" },
            { "World", "\xE909" },
            { "Comment", "\xE90A" },
            { "MusicInfo", "\xE90B" },
            { "DockLeft", "\xE90C" },
            { "DockRight", "\xE90D" },
            { "DockBottom", "\xE90E" },
            { "Repair", "\xE90F" },
            { "Accounts", "\xE910" },
            { "DullSound", "\xE911" },
            { "Manage", "\xE912" },
            { "Street", "\xE913" },
            { "Printer3D", "\xE914" },
            { "RadioBullet", "\xE915" },
            { "Stopwatch", "\xE916" },
            { "Photo", "\xE91B" },
            { "ActionCenter", "\xE91C" },
            { "FullCircleMask", "\xE91F" },
            { "ChromeMinimize", "\xE921" },
            { "ChromeMaximize", "\xE922" },
            { "ChromeRestore", "\xE923" },
            { "Annotation", "\xE924" },
            { "BackSpaceQWERTYSm", "\xE925" },
            { "BackSpaceQWERTYMd", "\xE926" },
            { "Swipe", "\xE927" },
            { "Fingerprint", "\xE928" },
            { "Handwriting", "\xE929" },
            { "ChromeBackToWindow", "\xE92C" },
            { "ChromeFullScreen", "\xE92D" },
            { "KeyboardStandard", "\xE92E" },
            { "KeyboardDismiss", "\xE92F" },
            { "Completed", "\xE930" },
            { "ChromeAnnotate", "\xE931" },
            { "Label", "\xE932" },
            { "IBeam", "\xE933" },
            { "IBeamOutline", "\xE934" },
            { "FlickDown", "\xE935" },
            { "FlickUp", "\xE936" },
            { "FlickLeft", "\xE937" },
            { "FlickRight", "\xE938" },
            { "FeedbackApp", "\xE939" },
            { "MusicAlbum", "\xE93C" },
            { "Streaming", "\xE93E" },
            { "Code", "\xE943" },
            { "ReturnToWindow", "\xE944" },
            { "LightningBolt", "\xE945" },
            { "Info", "\xE946" },
            { "CalculatorMultiply", "\xE947" },
            { "CalculatorAddition", "\xE948" },
            { "CalculatorSubtract", "\xE949" },
            { "CalculatorDivide", "\xE94A" },
            { "CalculatorSquareroot", "\xE94B" },
            { "CalculatorPercentage", "\xE94C" },
            { "CalculatorNegate", "\xE94D" },
            { "CalculatorEqualTo", "\xE94E" },
            { "CalculatorBackspace", "\xE94F" },
            { "Component", "\xE950" },
            { "DMC", "\xE951" },
            { "Dock", "\xE952" },
            { "MultimediaDMS", "\xE953" },
            { "MultimediaDVR", "\xE954" },
            { "MultimediaPMP", "\xE955" },
            { "PrintfaxPrinterFile", "\xE956" },
            { "Sensor", "\xE957" },
            { "StorageOptical", "\xE958" },
            { "Communications", "\xE95A" },
            { "Headset", "\xE95B" },
            { "Projector", "\xE95D" },
            { "Health", "\xE95E" },
            { "Wire", "\xE95F" },
            { "Webcam2", "\xE960" },
            { "Input", "\xE961" },
            { "Mouse", "\xE962" },
            { "Smartcard", "\xE963" },
            { "SmartcardVirtual", "\xE964" },
            { "MediaStorageTower", "\xE965" },
            { "ReturnKeySm", "\xE966" },
            { "GameConsole", "\xE967" },
            { "Network", "\xE968" },
            { "StorageNetworkWireless", "\xE969" },
            { "StorageTape", "\xE96A" },
            { "ChevronUpSmall", "\xE96D" },
            { "ChevronDownSmall", "\xE96E" },
            { "ChevronLeftSmall", "\xE96F" },
            { "ChevronRightSmall", "\xE970" },
            { "ChevronUpMed", "\xE971" },
            { "ChevronDownMed", "\xE972" },
            { "ChevronLeftMed", "\xE973" },
            { "ChevronRightMed", "\xE974" },
            { "Devices2", "\xE975" },
            { "ExpandTile", "\xE976" },
            { "PC1", "\xE977" },
            { "PresenceChicklet", "\xE978" },
            { "PresenceChickletVideo", "\xE979" },
            { "Reply", "\xE97A" },
            { "SetTile", "\xE97B" },
            { "Type", "\xE97C" },
            { "Korean", "\xE97D" },
            { "HalfAlpha", "\xE97E" },
            { "FullAlpha", "\xE97F" },
            { "Key12On", "\xE980" },
            { "ChineseChangjie", "\xE981" },
            { "QWERTYOn", "\xE982" },
            { "QWERTYOff", "\xE983" },
            { "ChineseQuick", "\xE984" },
            { "Japanese", "\xE985" },
            { "FullHiragana", "\xE986" },
            { "FullKatakana", "\xE987" },
            { "HalfKatakana", "\xE988" },
            { "ChineseBoPoMoFo", "\xE989" },
            { "ChinesePinyin", "\xE98A" },
            { "ConstructionCone", "\xE98F" },
            { "XboxOneConsole", "\xE990" },
            { "Volume0", "\xE992" },
            { "Volume1", "\xE993" },
            { "Volume2", "\xE994" },
            { "Volume3", "\xE995" },
            { "BatteryUnknown", "\xE996" },
            { "WifiAttentionOverlay", "\xE998" },
            { "Robot", "\xE99A" },
            { "TapAndSend", "\xE9A1" },
            { "FitPage", "\xE9A6" },
            { "PasswordKeyShow", "\xE9A8" },
            { "PasswordKeyHide", "\xE9A9" },
            { "BidiLtr", "\xE9AA" },
            { "BidiRtl", "\xE9AB" },
            { "ForwardSm", "\xE9AC" },
            { "CommaKey", "\xE9AD" },
            { "DashKey", "\xE9AE" },
            { "DullSoundKey", "\xE9AF" },
            { "HalfDullSound", "\xE9B0" },
            { "RightDoubleQuote", "\xE9B1" },
            { "LeftDoubleQuote", "\xE9B2" },
            { "PuncKeyRightBottom", "\xE9B3" },
            { "PuncKey1", "\xE9B4" },
            { "PuncKey2", "\xE9B5" },
            { "PuncKey3", "\xE9B6" },
            { "PuncKey4", "\xE9B7" },
            { "PuncKey5", "\xE9B8" },
            { "PuncKey6", "\xE9B9" },
            { "PuncKey9", "\xE9BA" },
            { "PuncKey7", "\xE9BB" },
            { "PuncKey8", "\xE9BC" },
            { "Frigid", "\xE9CA" },
            { "Unknown", "\xE9CE" },
            { "AreaChart", "\xE9D2" },
            { "CheckList", "\xE9D5" },
            { "Diagnostic", "\xE9D9" },
            { "Equalizer", "\xE9E9" },
            { "Process", "\xE9F3" },
            { "Processing", "\xE9F5" },
            { "ReportDocument", "\xE9F9" },

            { "VideoSolid", "\xEA0C" },
            { "MixedMediaBadge", "\xEA0D" },
            { "DisconnectDisplay", "\xEA14" },
            { "Shield", "\xEA18" },
            { "Info2", "\xEA1F" },
            { "ActionCenterAsterisk", "\xEA21" },
            { "Beta", "\xEA24" },
            { "SaveCopy", "\xEA35" },
            { "List", "\xEA37" },
            { "Asterisk", "\xEA38" },
            { "ErrorBadge", "\xEA39" },
            { "CircleRing", "\xEA3A" },
            { "CircleFill", "\xEA3B" },
            { "MergeCall", "\xEA3C" },
            { "PrivateCall", "\xEA3D" },
            { "Record2", "\xEA3F" },
            { "AllAppsMirrored", "\xEA40" },
            { "BookmarksMirrored", "\xEA41" },
            { "BulletedListMirrored", "\xEA42" },
            { "CallForwardInternationalMirrored", "\xEA43" },
            { "CallForwardRoamingMirrored", "\xEA44" },
            { "ChromeBackMirrored", "\xEA47" },
            { "ClearSelectionMirrored", "\xEA48" },
            { "ClosePaneMirrored", "\xEA49" },
            { "ContactInfoMirrored", "\xEA4A" },
            { "DockRightMirrored", "\xEA4B" },
            { "DockLeftMirrored", "\xEA4C" },
            { "ExpandTileMirrored", "\xEA4E" },
            { "GoMirrored", "\xEA4F" },
            { "GripperResizeMirrored", "\xEA50" },
            { "HelpMirrored", "\xEA51" },
            { "ImportMirrored", "\xEA52" },
            { "ImportAllMirrored", "\xEA53" },
            { "LeaveChatMirrored", "\xEA54" },
            { "ListMirrored", "\xEA55" },
            { "MailForwardMirrored", "\xEA56" },
            { "MailReplyMirrored", "\xEA57" },
            { "MailReplyAllMirrored", "\xEA58" },
            { "OpenPaneMirrored", "\xEA5B" },
            { "OpenWithMirrored", "\xEA5C" },
            { "ParkingLocationMirrored", "\xEA5E" },
            { "ResizeMouseMediumMirrored", "\xEA5F" },
            { "ResizeMouseSmallMirrored", "\xEA60" },
            { "ResizeMouseTallMirrored", "\xEA61" },
            { "ResizeTouchNarrowerMirrored", "\xEA62" },
            { "SendMirrored", "\xEA63" },
            { "SendFillMirrored", "\xEA64" },
            { "ShowResultsMirrored", "\xEA65" },
            { "Media", "\xEA69" },
            { "SyncError", "\xEA6A" },
            { "Devices3", "\xEA6C" },
            { "SlowMotionOn", "\xEA79" },
            { "Lightbulb", "\xEA80" },
            { "StatusCircle", "\xEA81" },
            { "StatusTriangle", "\xEA82" },
            { "StatusError", "\xEA83" },
            { "StatusWarning", "\xEA84" },
            { "Puzzle", "\xEA86" },
            { "CalendarSolid", "\xEA89" },
            { "HomeSolid", "\xEA8A" },
            { "ParkingLocationSolid", "\xEA8B" },
            { "ContactSolid", "\xEA8C" },
            { "ConstructionSolid", "\xEA8D" },
            { "AccidentSolid", "\xEA8E" },
            { "Ringer", "\xEA8F" },
            { "PDF", "\xEA90" },
            { "ThoughtBubble", "\xEA91" },
            { "HeartBroken", "\xEA92" },
            { "BatteryCharging10", "\xEA93" },
            { "BatterySaver9", "\xEA94" },
            { "BatterySaver10", "\xEA95" },
            { "CallForwardingMirrored", "\xEA97" },
            { "MultiSelectMirrored", "\xEA98" },
            { "Broom", "\xEA99" },
            { "ForwardCall", "\xEAC2" },
            { "Trackers", "\xEADF" },
            { "Market", "\xEAFC" },
            { "PieSingle", "\xEB05" },
            { "StockDown", "\xEB0F" },
            { "StockUp", "\xEB11" },
            { "Design", "\xEB3C" },
            { "Website", "\xEB41" },
            { "Drop", "\xEB42" },
            { "Radar", "\xEB44" },
            { "BusSolid", "\xEB47" },
            { "FerrySolid", "\xEB48" },
            { "StartPointSolid", "\xEB49" },
            { "StopPointSolid", "\xEB4A" },
            { "EndPointSolid", "\xEB4B" },
            { "AirplaneSolid", "\xEB4C" },
            { "TrainSolid", "\xEB4D" },
            { "WorkSolid", "\xEB4E" },
            { "ReminderFill", "\xEB4F" },
            { "Reminder", "\xEB50" },
            { "Heart", "\xEB51" },
            { "HeartFill", "\xEB52" },
            { "EthernetError", "\xEB55" },
            { "EthernetWarning", "\xEB56" },
            { "StatusConnecting1", "\xEB57" },
            { "StatusConnecting2", "\xEB58" },
            { "StatusUnsecure", "\xEB59" },
            { "WifiError0", "\xEB5A" },
            { "WifiError1", "\xEB5B" },
            { "WifiError2", "\xEB5C" },
            { "WifiError3", "\xEB5D" },
            { "WifiError4", "\xEB5E" },
            { "WifiWarning0", "\xEB5F" },
            { "WifiWarning1", "\xEB60" },
            { "WifiWarning2", "\xEB61" },
            { "WifiWarning3", "\xEB62" },
            { "WifiWarning4", "\xEB63" },
            { "Devices4", "\xEB66" },
            { "NUIIris", "\xEB67" },
            { "NUIFace", "\xEB68" },
            { "EditMirrored", "\xEB7E" },
            { "NUIFPStartSlideHand", "\xEB82" },
            { "NUIFPStartSlideAction", "\xEB83" },
            { "NUIFPContinueSlideHand", "\xEB84" },
            { "NUIFPContinueSlideAction", "\xEB85" },
            { "NUIFPRollRightHand", "\xEB86" },
            { "NUIFPRollRightHandAction", "\xEB87" },
            { "NUIFPRollLeftHand", "\xEB88" },
            { "NUIFPRollLeftAction", "\xEB89" },
            { "NUIFPPressHand", "\xEB8A" },
            { "NUIFPPressAction", "\xEB8B" },
            { "NUIFPPressRepeatHand", "\xEB8C" },
            { "NUIFPPressRepeatAction", "\xEB8D" },
            { "StatusErrorFull", "\xEB90" },
            { "TaskViewExpanded", "\xEB91" },
            { "Certificate", "\xEB95" },
            { "BackSpaceQWERTYLg", "\xEB96" },
            { "ReturnKeyLg", "\xEB97" },
            { "FastForward", "\xEB9D" },
            { "Rewind", "\xEB9E" },
            { "Photo2", "\xEB9F" },
            { "MobBattery0", "\xEBA0" },
            { "MobBattery1", "\xEBA1" },
            { "MobBattery2", "\xEBA2" },
            { "MobBattery3", "\xEBA3" },
            { "MobBattery4", "\xEBA4" },
            { "MobBattery5", "\xEBA5" },
            { "MobBattery6", "\xEBA6" },
            { "MobBattery7", "\xEBA7" },
            { "MobBattery8", "\xEBA8" },
            { "MobBattery9", "\xEBA9" },
            { "MobBattery10", "\xEBAA" },
            { "MobBatteryCharging0", "\xEBAB" },
            { "MobBatteryCharging1", "\xEBAC" },
            { "MobBatteryCharging2", "\xEBAD" },
            { "MobBatteryCharging3", "\xEBAE" },
            { "MobBatteryCharging4", "\xEBAF" },
            { "MobBatteryCharging5", "\xEBB0" },
            { "MobBatteryCharging6", "\xEBB1" },
            { "MobBatteryCharging7", "\xEBB2" },
            { "MobBatteryCharging8", "\xEBB3" },
            { "MobBatteryCharging9", "\xEBB4" },
            { "MobBatteryCharging10", "\xEBB5" },
            { "MobBatterySaver0", "\xEBB6" },
            { "MobBatterySaver1", "\xEBB7" },
            { "MobBatterySaver2", "\xEBB8" },
            { "MobBatterySaver3", "\xEBB9" },
            { "MobBatterySaver4", "\xEBBA" },
            { "MobBatterySaver5", "\xEBBB" },
            { "MobBatterySaver6", "\xEBBC" },
            { "MobBatterySaver7", "\xEBBD" },
            { "MobBatterySaver8", "\xEBBE" },
            { "MobBatterySaver9", "\xEBBF" },
            { "MobBatterySaver10", "\xEBC0" },
            { "DictionaryCloud", "\xEBC3" },
            { "ResetDrive", "\xEBC4" },
            { "VolumeBars", "\xEBC5" },
            { "Project", "\xEBC6" },
            { "AdjustHologram", "\xEBD2" },
            { "WifiCallBars", "\xEBD4" },
            { "WifiCall0", "\xEBD5" },
            { "WifiCall1", "\xEBD6" },
            { "WifiCall2", "\xEBD7" },
            { "WifiCall3", "\xEBD8" },
            { "WifiCall4", "\xEBD9" },
            { "Family", "\xEBDA" },
            { "LockFeedback", "\xEBDB" },
            { "DeviceDiscovery", "\xEBDE" },
            { "WindDirection", "\xEBE6" },
            { "RightArrowKeyTime0", "\xEBE7" },
            { "Bug", "\xEBE8" },
            { "TabletMode", "\xEBFC" },
            { "StatusCircleLeft", "\xEBFD" },
            { "StatusTriangleLeft", "\xEBFE" },
            { "StatusErrorLeft", "\xEBFF" },
            { "StatusWarningLeft", "\xEC00" },
            { "MobBatteryUnknown", "\xEC02" },
            { "NetworkTower", "\xEC05" },
            { "CityNext", "\xEC06" },
            { "CityNext2", "\xEC07" },
            { "Courthouse", "\xEC08" },
            { "Groceries", "\xEC09" },
            { "Sustainable", "\xEC0A" },
            { "BuildingEnergy", "\xEC0B" },
            { "ToggleFilled", "\xEC11" },
            { "ToggleBorder", "\xEC12" },
            { "SliderThumb", "\xEC13" },
            { "ToggleThumb", "\xEC14" },
            { "MiracastLogoSmall", "\xEC15" },
            { "MiracastLogoLarge", "\xEC16" },
            { "PLAP", "\xEC19" },
            { "Badge", "\xEC1B" },
            { "SignalRoaming", "\xEC1E" },
            { "MobileLocked", "\xEC20" },
            { "InsiderHubApp", "\xEC24" },
            { "PersonalFolder", "\xEC25" },
            { "HomeGroup", "\xEC26" },
            { "MyNetwork", "\xEC27" },
            { "KeyboardFull", "\xEC31" },
            { "Cafe", "\xEC32" },
            { "MobSignal1", "\xEC37" },
            { "MobSignal2", "\xEC38" },
            { "MobSignal3", "\xEC39" },
            { "MobSignal4", "\xEC3A" },
            { "MobSignal5", "\xEC3B" },
            { "MobWifi1", "\xEC3C" },
            { "MobWifi2", "\xEC3D" },
            { "MobWifi3", "\xEC3E" },
            { "MobWifi4", "\xEC3F" },
            { "MobAirplane", "\xEC40" },
            { "MobBluetooth", "\xEC41" },
            { "MobActionCenter", "\xEC42" },
            { "MobLocation", "\xEC43" },
            { "MobWifiHotspot", "\xEC44" },
            { "LanguageJpn", "\xEC45" },
            { "MobQuietHours", "\xEC46" },
            { "MobDrivingMode", "\xEC47" },
            { "SpeedOff", "\xEC48" },
            { "SpeedMedium", "\xEC49" },
            { "SpeedHigh", "\xEC4A" },
            { "ThisPC", "\xEC4E" },
            { "MusicNote", "\xEC4F" },
            { "FileExplorer", "\xEC50" },
            { "FileExplorerApp", "\xEC51" },
            { "LeftArrowKeyTime0", "\xEC52" },
            { "MicOff", "\xEC54" },
            { "MicSleep", "\xEC55" },
            { "MicError", "\xEC56" },
            { "PlaybackRate1x", "\xEC57" },
            { "PlaybackRateOther", "\xEC58" },
            { "CashDrawer", "\xEC59" },
            { "BarcodeScanner", "\xEC5A" },
            { "ReceiptPrinter", "\xEC5B" },
            { "MagStripeReader", "\xEC5C" },
            { "CompletedSolid", "\xEC61" },
            { "CompanionApp", "\xEC64" },
            { "Favicon2", "\xEC6C" },
            { "SwipeRevealArt", "\xEC6D" },
            { "MicOn", "\xEC71" },
            { "MicClipping", "\xEC72" },
            { "TabletSelected", "\xEC74" },
            { "MobileSelected", "\xEC75" },
            { "LaptopSelected", "\xEC76" },
            { "TVMonitorSelected", "\xEC77" },
            { "DeveloperTools", "\xEC7A" },
            { "MobCallForwarding", "\xEC7E" },
            { "MobCallForwardingMirrored", "\xEC7F" },
            { "BodyCam", "\xEC80" },
            { "PoliceCar", "\xEC81" },
            { "Draw", "\xEC87" },
            { "DrawSolid", "\xEC88" },
            { "LowerBrightness", "\xEC8A" },
            { "ScrollUpDown", "\xEC8F" },
            { "DateTime", "\xEC92" },
            { "Tiles", "\xECA5" },
            { "PartyLeader", "\xECA7" },
            { "AppIconDefault", "\xECAA" },
            { "Calories", "\xECAD" },
            { "BandBattery0", "\xECB9" },
            { "BandBattery1", "\xECBA" },
            { "BandBattery2", "\xECBB" },
            { "BandBattery3", "\xECBC" },
            { "BandBattery4", "\xECBD" },
            { "BandBattery5", "\xECBE" },
            { "BandBattery6", "\xECBF" },
            { "AddSurfaceHub", "\xECC4" },
            { "DevUpdate", "\xECC5" },
            { "Unit", "\xECC6" },
            { "AddTo", "\xECC8" },
            { "RemoveFrom", "\xECC9" },
            { "RadioBtnOff", "\xECCA" },
            { "RadioBtnOn", "\xECCB" },
            { "RadioBullet2", "\xECCC" },
            { "ExploreContent", "\xECCD" },
            { "Blocked2", "\xECE4" },
            { "ScrollMode", "\xECE7" },
            { "ZoomMode", "\xECE8" },
            { "PanMode", "\xECE9" },
            { "WiredUSB", "\xECF0" },
            { "WirelessUSB", "\xECF1" },
            { "USBSafeConnect", "\xECF3" },

            { "ActionCenterNotificationMirrored", "\xED0C" },
            { "ActionCenterMirrored", "\xED0D" },
            { "SubscriptionAdd", "\xED0E" },
            { "ResetDevice", "\xED10" },
            { "SubscriptionAddMirrored", "\xED11" },
            { "QRCode", "\xED14" },
            { "Feedback", "\xED15" },
            { "Subtitles", "\xED1E" },
            { "SubtitlesAudio", "\xED1F" },
            { "OpenFolderHorizontal", "\xED25" },
            { "CalendarMirrored", "\xED28" },
            { "MobeSIM", "\xED2A" },
            { "MobeSIMNoProfile", "\xED2B" },
            { "MobeSIMLocked", "\xED2C" },
            { "MobeSIMBusy", "\xED2D" },
            { "SignalError", "\xED2E" },
            { "StreamingEnterprise", "\xED2F" },
            { "Headphone0", "\xED30" },
            { "Headphone1", "\xED31" },
            { "Headphone2", "\xED32" },
            { "Headphone3", "\xED33" },
            { "Apps", "\xED35" },
            { "KeyboardBrightness", "\xED39" },
            { "KeyboardLowerBrightness", "\xED3A" },
            { "SkipBack10", "\xED3C" },
            { "SkipForward30", "\xED3D" },
            { "TreeFolderFolder", "\xED41" },
            { "TreeFolderFolderFill", "\xED42" },
            { "TreeFolderFolderOpen", "\xED43" },
            { "TreeFolderFolderOpenFill", "\xED44" },
            { "MultimediaDMP", "\xED47" },
            { "KeyboardOneHanded", "\xED4C" },
            { "Narrator", "\xED4D" },
            { "EmojiTabPeople", "\xED53" },
            { "EmojiTabSmilesAnimals", "\xED54" },
            { "EmojiTabCelebrationObjects", "\xED55" },
            { "EmojiTabFoodPlants", "\xED56" },
            { "EmojiTabTransitPlaces", "\xED57" },
            { "EmojiTabSymbols", "\xED58" },
            { "EmojiTabTextSmiles", "\xED59" },
            { "EmojiTabFavorites", "\xED5A" },
            { "EmojiSwatch", "\xED5B" },
            { "ConnectApp", "\xED5C" },
            { "CompanionDeviceFramework", "\xED5D" },
            { "Ruler", "\xED5E" },
            { "FingerInking", "\xED5F" },
            { "StrokeErase", "\xED60" },
            { "PointErase", "\xED61" },
            { "ClearAllInk", "\xED62" },
            { "Pencil", "\xED63" },
            { "Marker", "\xED64" },
            { "InkingCaret", "\xED65" },
            { "InkingColorOutline", "\xED66" },
            { "InkingColorFill", "\xED67" },
            { "HardDrive", "\xEDA2" },
            { "NetworkAdapter", "\xEDA3" },
            { "Touchscreen", "\xEDA4" },
            { "NetworkPrinter", "\xEDA5" },
            { "CloudPrinter", "\xEDA6" },
            { "KeyboardShortcut", "\xEDA7" },
            { "BrushSize", "\xEDA8" },
            { "NarratorForward", "\xEDA9" },
            { "NarratorForwardMirrored", "\xEDAA" },
            { "SyncBadge12", "\xEDAB" },
            { "RingerBadge12", "\xEDAC" },
            { "AsteriskBadge12", "\xEDAD" },
            { "ErrorBadge12", "\xEDAE" },
            { "CircleRingBadge12", "\xEDAF" },
            { "CircleFillBadge12", "\xEDB0" },
            { "ImportantBadge12", "\xEDB1" },
            { "MailBadge12", "\xEDB3" },
            { "PauseBadge12", "\xEDB4" },
            { "PlayBadge12", "\xEDB5" },
            { "PenWorkspace", "\xEDC6" },
            { "CaretRight8", "\xEDD6" },
            { "CaretLeftSolid8", "\xEDD9" },
            { "CaretRightSolid8", "\xEDDA" },
            { "CaretUpSolid8", "\xEDDB" },
            { "CaretDownSolid8", "\xEDDC" },
            { "Strikethrough", "\xEDE0" },
            { "Export", "\xEDE1" },
            { "ExportMirrored", "\xEDE2" },
            { "ButtonMenu", "\xEDE3" },
            { "CloudSearch", "\xEDE4" },
            { "PinyinIMELogo", "\xEDE5" },
            { "CalligraphyPen", "\xEDFB" },
            { "ReplyMirrored", "\xEE35" },
            { "LockscreenDesktop", "\xEE3F" },
            { "TaskViewSettings", "\xEE40" },
            { "MiniExpand2Mirrored", "\xEE47" },
            { "MiniContract2Mirrored", "\xEE49" },
            { "Play36", "\xEE4A" },
            { "PenPalette", "\xEE56" },
            { "GuestUser", "\xEE57" },
            { "SettingsBattery", "\xEE63" },
            { "TaskbarPhone", "\xEE64" },
            { "LockScreenGlance", "\xEE65" },
            { "GenericScan", "\xEE6F" },
            { "ImageExport", "\xEE71" },
            { "WifiEthernet", "\xEE77" },
            { "ActionCenterQuiet", "\xEE79" },
            { "ActionCenterQuietNotification", "\xEE7A" },
            { "TrackersMirrored", "\xEE92" },
            { "DateTimeMirrored", "\xEE93" },
            { "Wheel", "\xEE94" },
            { "VirtualMachineGroup", "\xEEA3" },
            { "ButtonView2", "\xEECA" },
            { "PenWorkspaceMirrored", "\xEF15" },
            { "PenPaletteMirrored", "\xEF16" },
            { "StrokeEraseMirrored", "\xEF17" },
            { "PointEraseMirrored", "\xEF18" },
            { "ClearAllInkMirrored", "\xEF19" },
            { "BackgroundToggle", "\xEF1F" },
            { "Marquee", "\xEF20" },
            { "ChromeCloseContrast", "\xEF2C" },
            { "ChromeMinimizeContrast", "\xEF2D" },
            { "ChromeMaximizeContrast", "\xEF2E" },
            { "ChromeRestoreContrast", "\xEF2F" },
            { "TrafficLight", "\xEF31" },
            { "Replay", "\xEF3B" },
            { "Eyedropper", "\xEF3C" },
            { "LineDisplay", "\xEF3D" },
            { "PINPad", "\xEF3E" },
            { "SignatureCapture", "\xEF3F" },
            { "ChipCardCreditCardReader", "\xEF40" },
            { "PlayerSettings", "\xEF58" },
            { "LandscapeOrientation", "\xEF6B" },
            { "Flow", "\xEF90" },
            { "Touchpad", "\xEFA5" },
            { "Speech", "\xEFA9" },

            { "KnowledgeArticle", "\xF000" },
            { "Relationship", "\xF003" },
            { "DefaultAPN", "\xF080" },
            { "UserAPN", "\xF081" },
            { "DoublePinyin", "\xF085" },
            { "BlueLight", "\xF08C" },
            { "ButtonA", "\xF093" },
            { "ButtonB", "\xF094" },
            { "ButtonY", "\xF095" },
            { "ButtonX", "\xF096" },
            { "ArrowUp8", "\xF0AD" },
            { "ArrowDown8", "\xF0AE" },
            { "ArrowRight8", "\xF0AF" },
            { "ArrowLeft8", "\xF0B0" },
            { "QuarentinedItems", "\xF0B2" },
            { "QuarentinedItemsMirrored", "\xF0B3" },
            { "Protractor", "\xF0B4" },
            { "ChecklistMirrored", "\xF0B5" },
            { "StatusCircle7", "\xF0B6" },
            { "StatusCheckmark7", "\xF0B7" },
            { "StatusErrorCircle7", "\xF0B8" },
            { "Connected", "\xF0B9" },
            { "PencilFill", "\xF0C6" },
            { "CalligraphyFill", "\xF0C7" },
            { "QuarterStarLeft", "\xF0CA" },
            { "QuarterStarRight", "\xF0CB" },
            { "ThreeQuarterStarLeft", "\xF0CC" },
            { "ThreeQuarterStarRight", "\xF0CD" },
            { "QuietHoursBadge12", "\xF0CE" },
            { "BackMirrored", "\xF0D2" },
            { "ForwardMirrored", "\xF0D3" },
            { "ChromeBackContrast", "\xF0D5" },
            { "ChromeBackContrastMirrored", "\xF0D6" },
            { "ChromeBackToWindowContrast", "\xF0D7" },
            { "ChromeFullScreenContrast", "\xF0D8" },
            { "GridView", "\xF0E2" },
            { "ClipboardList", "\xF0E3" },
            { "ClipboardListMirrored", "\xF0E4" },
            { "OutlineQuarterStarLeft", "\xF0E5" },
            { "OutlineQuarterStarRight", "\xF0E6" },
            { "OutlineHalfStarLeft", "\xF0E7" },
            { "OutlineHalfStarRight", "\xF0E8" },
            { "OutlineThreeQuarterStarLeft", "\xF0E9" },
            { "OutlineThreeQuarterStarRight", "\xF0EA" },
            { "SpatialVolume0", "\xF0EB" },
            { "SpatialVolume1", "\xF0EC" },
            { "SpatialVolume2", "\xF0ED" },
            { "SpatialVolume3", "\xF0EE" },
            { "ApplicationGuard", "\xF0EF" },
            { "OutlineStarLeftHalf", "\xF0F7" },
            { "OutlineStarRightHalf", "\xF0F8" },
            { "ChromeAnnotateContrast", "\xF0F9" },
            { "DefenderBadge12", "\xF0FB" },
            { "DetachablePC", "\xF103" },
            { "LeftStick", "\xF108" },
            { "RightStick", "\xF109" },
            { "TriggerLeft", "\xF10A" },
            { "TriggerRight", "\xF10B" },
            { "BumperLeft", "\xF10C" },
            { "BumperRight", "\xF10D" },
            { "Dpad", "\xF10E" },
            { "EnglishPunctuation", "\xF110" },
            { "ChinesePunctuation", "\xF111" },
            { "HMD", "\xF119" },
            { "CtrlSpatialRight", "\xF11B" },
            { "PaginationDotOutline10", "\xF126" },
            { "PaginationDotSolid10", "\xF127" },
            { "StrokeErase2", "\xF128" },
            { "SmallErase", "\xF129" },
            { "LargeErase", "\xF12A" },
            { "FolderHorizontal", "\xF12B" },
            { "MicrophoneListening", "\xF12E" },
            { "StatusExclamationCircle7", "\xF12F" },
            { "Video360", "\xF131" },
            { "GiftboxOpen", "\xF133" },
            { "StatusCircleOuter", "\xF136" },
            { "StatusCircleInner", "\xF137" },
            { "StatusCircleRing", "\xF138" },
            { "StatusTriangleOuter", "\xF139" },
            { "StatusTriangleInner", "\xF13A" },
            { "StatusTriangleExclamation", "\xF13B" },
            { "StatusCircleExclamation", "\xF13C" },
            { "StatusCircleErrorX", "\xF13D" },
            { "StatusCircleCheckmark", "\xF13E" },
            { "StatusCircleInfo", "\xF13F" },
            { "StatusCircleBlock", "\xF140" },
            { "StatusCircleBlock2", "\xF141" },
            { "StatusCircleQuestionMark", "\xF142" },
            { "StatusCircleSync", "\xF143" },
            { "Dial1", "\xF146" },
            { "Dial2", "\xF147" },
            { "Dial3", "\xF148" },
            { "Dial4", "\xF149" },
            { "Dial5", "\xF14A" },
            { "Dial6", "\xF14B" },
            { "Dial7", "\xF14C" },
            { "Dial8", "\xF14D" },
            { "Dial9", "\xF14E" },
            { "Dial10", "\xF14F" },
            { "Dial11", "\xF150" },
            { "Dial12", "\xF151" },
            { "Dial13", "\xF152" },
            { "Dial14", "\xF153" },
            { "Dial15", "\xF154" },
            { "Dial16", "\xF155" },
            { "DialShape1", "\xF156" },
            { "DialShape2", "\xF157" },
            { "DialShape3", "\xF158" },
            { "DialShape4", "\xF159" },
            { "TollSolid", "\xF161" },
            { "TrafficCongestionSolid", "\xF163" },
            { "ExploreContentSingle", "\xF164" },
            { "CollapseContent", "\xF165" },
            { "CollapseContentSingle", "\xF166" },
            { "InfoSolid", "\xF167" },
            { "GroupList", "\xF168" },
            { "CaretBottomRightSolidCenter8", "\xF169" },
            { "ProgressRingDots", "\xF16A" },
            { "Checkbox14", "\xF16B" },
            { "CheckboxComposite14", "\xF16C" },
            { "CheckboxIndeterminateCombo14", "\xF16D" },
            { "CheckboxIndeterminateCombo", "\xF16E" },
            { "StatusPause7", "\xF175" },
            { "CharacterAppearance", "\xF17F" },
            { "Lexicon", "\xF180" },
            { "ScreenTime", "\xF182" },
            { "HeadlessDevice", "\xF191" },
            { "NetworkSharing", "\xF193" },
            { "EyeGaze", "\xF19D" },
            { "ToggleLeft", "\xF19E" },
            { "ToggleRight", "\xF19F" },
            { "WindowsInsider", "\xF1AD" },
            { "ChromeSwitch", "\xF1CB" },
            { "ChromeSwitchContast", "\xF1CC" },
            { "StatusCheckmark", "\xF1D8" },
            { "StatusCheckmarkLeft", "\xF1D9" },
            { "KeyboardLeftAligned", "\xF20C" },
            { "KeyboardRightAligned", "\xF20D" },
            { "KeyboardSettings", "\xF210" },
            { "NetworkPhysical", "\xF211" },
            { "IOT", "\xF22C" },
            { "UnknownMirrored", "\xF22E" },
            { "ViewDashboard", "\xF246" },
            { "ExploitProtectionSettings", "\xF259" },
            { "KeyboardNarrow", "\xF260" },
            { "Keyboard12Key", "\xF261" },
            { "KeyboardDock", "\xF26B" },
            { "KeyboardUndock", "\xF26C" },
            { "KeyboardLeftDock", "\xF26D" },
            { "KeyboardRightDock", "\xF26E" },
            { "Ear", "\xF270" },
            { "PointerHand", "\xF271" },
            { "Bullseye", "\xF272" },
            { "LocaleLanguage", "\xF2B7" },

            { "PassiveAuthentication", "\xF32A" },
            { "ColorSolid", "\xF354" },
            { "NetworkOffline", "\xF384" },
            { "NetworkConnected", "\xF385" },
            { "NetworkConnectedCheckmark", "\xF386" },
            { "SignOut", "\xF3B1" },
            { "StatusInfo", "\xF3CC" },
            { "StatusInfoLeft", "\xF3CD" },
            { "NearbySharing", "\xF3E2" },
            { "CtrlSpatialLeft", "\xF3E7" },
            { "InteractiveDashboard", "\xF404" },
            { "ClippingTool", "\xF406" },
            { "RectangularClipping", "\xF407" },
            { "FreeFormClipping", "\xF408" },
            { "CopyTo", "\xF413" },
            { "DynamicLock", "\xF439" },
            { "PenTips", "\xF45E" },
            { "PenTipsMirrored", "\xF45F" },
            { "HWPJoin", "\xF460" },
            { "HWPInsert", "\xF461" },
            { "HWPStrikeThrough", "\xF462" },
            { "HWPScratchOut", "\xF463" },
            { "HWPSplit", "\xF464" },
            { "HWPNewLine", "\xF465" },
            { "HWPOverwrite", "\xF466" },
            { "MobWifiWarning1", "\xF473" },
            { "MobWifiWarning2", "\xF474" },
            { "MobWifiWarning3", "\xF475" },
            { "MobWifiWarning4", "\xF476" },
            { "Globe2", "\xF49A" },
            { "SpecialEffectSize", "\xF4A5" },
            { "GIF", "\xF4A9" },
            { "Sticker2", "\xF4AA" },
            { "SurfaceHubSelected", "\xF4BE" },
            { "HoloLensSelected", "\xF4BF" },
            { "Earbud", "\xF4C0" },
            { "MixVolumes", "\xF4C3" },
            { "Safe", "\xF540" },
            { "LaptopSecure", "\xF552" },
            { "PrintDefault", "\xF56D" },
            { "PageMirrored", "\xF56E" },
            { "LandscapeOrientationMirrored", "\xF56F" },
            { "ColorOff", "\xF570" },
            { "PrintAllPages", "\xF571" },
            { "PrintCustomRange", "\xF572" },
            { "PageMarginPortraitNarrow", "\xF573" },
            { "PageMarginPortraitNormal", "\xF574" },
            { "PageMarginPortraitModerate", "\xF575" },
            { "PageMarginPortraitWide", "\xF576" },
            { "PageMarginLandscapeNarrow", "\xF577" },
            { "PageMarginLandscapeNormal", "\xF578" },
            { "PageMarginLandscapeModerate", "\xF579" },
            { "PageMarginLandscapeWide", "\xF57A" },
            { "CollateLandscape", "\xF57B" },
            { "CollatePortrait", "\xF57C" },
            { "CollatePortraitSeparated", "\xF57D" },
            { "DuplexLandscapeOneSided", "\xF57E" },
            { "DuplexLandscapeOneSidedMirrored", "\xF57F" },
            { "DuplexLandscapeTwoSidedLongEdge", "\xF580" },
            { "DuplexLandscapeTwoSidedLongEdgeMirrored", "\xF581" },
            { "DuplexLandscapeTwoSidedShortEdge", "\xF582" },
            { "DuplexLandscapeTwoSidedShortEdgeMirrored", "\xF583" },
            { "DuplexPortraitOneSided", "\xF584" },
            { "DuplexPortraitOneSidedMirrored", "\xF585" },
            { "DuplexPortraitTwoSidedLongEdge", "\xF586" },
            { "DuplexPortraitTwoSidedLongEdgeMirrored", "\xF587" },
            { "DuplexPortraitTwoSidedShortEdge", "\xF588" },
            { "DuplexPortraitTwoSidedShortEdgeMirrored", "\xF589" },
            { "PPSOneLandscape", "\xF58A" },
            { "PPSTwoLandscape", "\xF58B" },
            { "PPSTwoPortrait", "\xF58C" },
            { "PPSFourLandscape", "\xF58D" },
            { "PPSFourPortrait", "\xF58E" },
            { "HolePunchOff", "\xF58F" },
            { "HolePunchPortraitLeft", "\xF590" },
            { "HolePunchPortraitRight", "\xF591" },
            { "HolePunchPortraitTop", "\xF592" },
            { "HolePunchPortraitBottom", "\xF593" },
            { "HolePunchLandscapeLeft", "\xF594" },
            { "HolePunchLandscapeRight", "\xF595" },
            { "HolePunchLandscapeTop", "\xF596" },
            { "HolePunchLandscapeBottom", "\xF597" },
            { "StaplingOff", "\xF598" },
            { "StaplingPortraitTopLeft", "\xF599" },
            { "StaplingPortraitTopRight", "\xF59A" },
            { "StaplingPortraitBottomRight", "\xF59B" },
            { "StaplingPortraitTwoLeft", "\xF59C" },
            { "StaplingPortraitTwoRight", "\xF59D" },
            { "StaplingPortraitTwoTop", "\xF59E" },
            { "StaplingPortraitTwoBottom", "\xF59F" },
            { "StaplingPortraitBookBinding", "\xF5A0" },
            { "StaplingLandscapeTopLeft", "\xF5A1" },
            { "StaplingLandscapeTopRight", "\xF5A2" },
            { "StaplingLandscapeBottomLeft", "\xF5A3" },
            { "StaplingLandscapeBottomRight", "\xF5A4" },
            { "StaplingLandscapeTwoLeft", "\xF5A5" },
            { "StaplingLandscapeTwoRight", "\xF5A6" },
            { "StaplingLandscapeTwoTop", "\xF5A7" },
            { "StaplingLandscapeTwoBottom", "\xF5A8" },
            { "StaplingLandscapeBookBinding", "\xF5A9" },
            { "StatusDataTransferRoaming", "\xF5AA" },
            { "MobSIMError", "\xF5AB" },
            { "CollateLandscapeSeparated", "\xF5AC" },
            { "PPSOnePortrait", "\xF5AD" },
            { "StaplingPortraitBottomLeft", "\xF5AE" },
            { "PlaySolid", "\xF5B0" },
            { "RepeatOff", "\xF5E7" },
            { "Set", "\xF5ED" },
            { "SetSolid", "\xF5EE" },
            { "FuzzyReading", "\xF5EF" },
            { "VerticalBattery0", "\xF5F2" },
            { "VerticalBattery1", "\xF5F3" },
            { "VerticalBattery2", "\xF5F4" },
            { "VerticalBattery3", "\xF5F5" },
            { "VerticalBattery4", "\xF5F6" },
            { "VerticalBattery5", "\xF5F7" },
            { "VerticalBattery6", "\xF5F8" },
            { "VerticalBattery7", "\xF5F9" },
            { "VerticalBattery8", "\xF5FA" },
            { "VerticalBattery9", "\xF5FB" },
            { "VerticalBattery10", "\xF5FC" },
            { "VerticalBatteryCharging0", "\xF5FD" },
            { "VerticalBatteryCharging1", "\xF5FE" },
            { "VerticalBatteryCharging2", "\xF5FF" },

            { "VerticalBatteryCharging3", "\xF600" },
            { "VerticalBatteryCharging4", "\xF601" },
            { "VerticalBatteryCharging5", "\xF602" },
            { "VerticalBatteryCharging6", "\xF603" },
            { "VerticalBatteryCharging7", "\xF604" },
            { "VerticalBatteryCharging8", "\xF605" },
            { "VerticalBatteryCharging9", "\xF606" },
            { "VerticalBatteryCharging10", "\xF607" },
            { "VerticalBatteryUnknown", "\xF608" },
            { "DoublePortrait", "\xF614" },
            { "DoubleLandscape", "\xF615" },
            { "SinglePortrait", "\xF616" },
            { "SingleLandscape", "\xF617" },
            { "SIMError", "\xF618" },
            { "SIMMissing", "\xF619" },
            { "SIMLock", "\xF61A" },
            { "eSIM", "\xF61B" },
            { "eSIMNoProfile", "\xF61C" },
            { "eSIMLocked", "\xF61D" },
            { "eSIMBusy", "\xF61E" },
            { "NoiseCancelation", "\xF61F" },
            { "NoiseCancelationOff", "\xF620" },
            { "MusicSharing", "\xF623" },
            { "MusicSharingOff", "\xF624" },
            { "CircleShapeSolid", "\xF63C" },
            { "CHTLanguageBar", "\xF69E" },
            { "ComposeMode", "\xF6A9" },
            { "ExpressiveInputEntry", "\xF6B8" },
            { "EmojiTabMoreSymbols", "\xF6BA" },
            { "WebSearch", "\xF6FA" },
            { "Kiosk", "\xF712" },
            { "RTTLogo", "\xF714" },
            { "VoiceCall", "\xF715" },
            { "GoToMessage", "\xF716" },
            { "ReturnToCall", "\xF71A" },
            { "StartPresenting", "\xF71C" },
            { "StopPresenting", "\xF71D" },
            { "ProductivityMode", "\xF71E" },
            { "SetHistoryStatus", "\xF738" },
            { "SetHistoryStatus2", "\xF739" },
            { "Keyboardsettings20", "\xF73D" },
            { "OneHandedRight20", "\xF73E" },
            { "OneHandedLeft20", "\xF73F" },
            { "Split20", "\xF740" },
            { "Full20", "\xF741" },
            { "Handwriting20", "\xF742" },
            { "CheveronLeft20", "\xF743" },
            { "CheveronLeft32", "\xF744" },
            { "CheveronRight20", "\xF745" },
            { "CheveronRight32", "\xF746" },
            { "MicOff2", "\xF781" },
            { "DeliveryOptimization", "\xF785" },
            { "CancelMedium", "\xF78A" },
            { "SearchMedium", "\xF78B" },
            { "AcceptMedium", "\xF78C" },
            { "RevealPasswordMedium", "\xF78D" },
            { "DeleteWord", "\xF7AD" },
            { "DeleteWordFill", "\xF7AE" },
            { "DeleteLines", "\xF7AF" },
            { "DeleteLinesFill", "\xF7B0" },
            { "InstertWords", "\xF7B1" },
            { "InstertWordsFill", "\xF7B2" },
            { "JoinWords", "\xF7B3" },
            { "JoinWordsFill", "\xF7B4" },
            { "OverwriteWords", "\xF7B5" },
            { "OverwriteWordsFill", "\xF7B6" },
            { "AddNewLine", "\xF7B7" },
            { "AddNewLineFill", "\xF7B8" },
            { "OverwriteWordsKorean", "\xF7B9" },
            { "OverwriteWordsFillKorean", "\xF7BA" },
            { "EducationIcon", "\xF7BB" },
            { "WindowSnipping", "\xF7ED" },
            { "VideoCapture", "\xF7EE" },
            { "StatusSecured", "\xF809" },
            { "NarratorApp", "\xF83B" },
            { "PowerButtonUpdate", "\xF83D" },
            { "RestartUpdate", "\xF83E" },
            { "UpdateStatusDot", "\xF83F" },
            { "Eject", "\xF847" },
            { "Spelling", "\xF87B" },
            { "SpellingKorean", "\xF87C" },
            { "SpellingSerbian", "\xF87D" },
            { "SpellingChinese", "\xF87E" },
            { "FolderSelect", "\xF89A" },
            { "SmartScreen", "\xF8A5" },
            { "ExploitProtection", "\xF8A6" },
            { "AddBold", "\xF8AA" },
            { "SubtractBold", "\xF8AB" },
            { "BackSolidBold", "\xF8AC" },
            { "ForwardSolidBold", "\xF8AD" },
            { "PauseBold", "\xF8AE" },
            { "ClickSolid", "\xF8AF" },
            { "SettingsSolid", "\xF8B0" },
            { "MicrophoneSolidBold", "\xF8B1" },
            { "SpeechSolidBold", "\xF8B2" },
            { "ClickedOutLoudSolidBold", "\xF8B3" }
        };

        public static string GetIcon(FontIcon iconName)
        {
            return _icons[iconName.ToString()];
        }
    }

    public enum FontIcon
    {
        GlobalNavigationButton,
        Wifi,
        Bluetooth,
        Connect,
        InternetSharing,
        VPN,
        Brightness,
        MapPin,
        QuietHours,
        Airplane,
        Tablet,
        QuickNote,
        RememberedDevice,
        ChevronDown,
        ChevronUp,
        Edit,
        Add,
        Cancel,
        More,
        Setting,
        Video,
        Mail,
        People,
        Phone,
        Pin,
        Shop,
        Stop,
        Link,
        Filter,
        AllApps,
        Zoom,
        ZoomOut,
        Microphone,
        Search,
        Camera,
        Attach,
        Send,
        SendFill,
        WalkSolid,
        InPrivate,
        FavoriteList,
        PageSolid,
        Forward,
        Back,
        Refresh,
        Share,
        Lock,
        ReportHacked,
        EMI,
        FavoriteStar,
        FavoriteStarFill,
        ReadingMode,
        Favicon,
        Remove,
        Checkbox,
        CheckboxComposite,
        CheckboxFill,
        CheckboxIndeterminate,
        CheckboxCompositeReversed,
        CheckMark,
        BackToWindow,
        FullScreen,
        ResizeTouchLarger,
        ResizeTouchSmaller,
        ResizeMouseSmall,
        ResizeMouseMedium,
        ResizeMouseWide,
        ResizeMouseTall,
        ResizeMouseLarge,
        SwitchUser,
        Print,
        Up,
        Down,
        OEM,
        Delete,
        Save,
        Mute,
        BackSpaceQWERTY,
        ReturnKey,
        UpArrowShiftKey,
        Cloud,
        Flashlight,
        RotationLock,
        CommandPrompt,
        SIPMove,
        SIPUndock,
        SIPRedock,
        EraseTool,
        UnderscoreSpace,
        GripperTool,
        Dialpad,
        PageLeft,
        PageRight,
        MultiSelect,
        KeyboardLeftHanded,
        KeyboardRightHanded,
        KeyboardClassic,
        KeyboardSplit,
        Volume,
        Play,
        Pause,
        ChevronLeft,
        ChevronRight,
        InkingTool,
        Emoji2,
        GripperBarHorizontal,
        System,
        Personalize,
        Devices,
        SearchAndApps,
        Globe,
        TimeLanguage,
        EaseOfAccess,
        UpdateRestore,
        HangUp,
        ContactInfo,
        Unpin,
        Contact,
        Memo,
        IncomingCall,
        Paste,
        PhoneBook,
        LEDLight,
        Error,
        GripperBarVertical,
        Unlock,
        Slideshow,
        Calendar,
        GripperResize,
        Megaphone,
        Trim,
        NewWindow,
        SaveLocal,
        Color,
        DataSense,
        SaveAs,
        Light,
        AspectRatio,
        DataSenseBar,
        Redo,
        Undo,
        Crop,
        OpenWith,
        Rotate,
        RedEye,
        SetlockScreen,
        MapPin2,
        Package,
        Warning,
        ReadingList,
        Education,
        ShoppingCart,
        Train,
        Flag,
        Page,
        TaskView,
        BrowsePhotos,
        HalfStarLeft,
        HalfStarRight,
        Record,
        TouchPointer,
        LangJPN,
        Ferry,
        Highlight,
        ActionCenterNotification,
        PowerButton,
        ResizeTouchNarrower,
        ResizeTouchShorter,
        DrivingMode,
        RingerSilent,
        OtherUser,
        Admin,
        CC,
        SDCard,
        CallForwarding,
        SettingsDisplaySound,
        TVMonitor,
        Speakers,
        Headphone,
        DeviceLaptopPic,
        DeviceLaptopNoPic,
        DeviceMonitorRightPic,
        DeviceMonitorLeftPic,
        DeviceMonitorNoPic,
        Game,
        HorizontalTabKey,
        StreetsideSplitMinimize,
        StreetsideSplitExpand,
        Car,
        Walk,
        Bus,
        TiltUp,
        TiltDown,
        CallControl,
        RotateMapRight,
        RotateMapLeft,
        Home,
        ParkingLocation,
        MapCompassTop,
        MapCompassBottom,
        IncidentTriangle,
        Touch,
        MapDirections,
        StartPoint,
        StopPoint,
        EndPoint,
        History,
        Location,
        MapLayers,
        Accident,
        Work,
        Construction,
        Recent,
        Bank,
        DownloadMap,
        InkingToolFill2,
        HighlightFill2,
        EraseToolFill,
        EraseToolFill2,
        Dictionary,
        DictionaryAdd,
        ToolTip,
        ChromeBack,
        ProvisioningPackage,
        AddRemoteDevice,
        FolderOpen,
        Ethernet,
        ShareBroadband,
        DirectAccess,
        DialUp,
        DefenderApp,
        BatteryCharging9,
        Battery10,
        Pinned,
        PinFill,
        PinnedFill,
        PeriodKey,
        PuncKey,
        RevToggleKey,
        RightArrowKeyTime1,
        RightArrowKeyTime2,
        LeftQuote,
        RightQuote,
        DownShiftKey,
        UpShiftKey,
        PuncKey0,
        PuncKeyLeftBottom,
        RightArrowKeyTime3,
        RightArrowKeyTime4,
        Battery0,
        Battery1,
        Battery2,
        Battery3,
        Battery4,
        Battery5,
        Battery6,
        Battery7,
        Battery8,
        Battery9,
        BatteryCharging0,
        BatteryCharging1,
        BatteryCharging2,
        BatteryCharging3,
        BatteryCharging4,
        BatteryCharging5,
        BatteryCharging6,
        BatteryCharging7,
        BatteryCharging8,
        BatterySaver0,
        BatterySaver1,
        BatterySaver2,
        BatterySaver3,
        BatterySaver4,
        BatterySaver5,
        BatterySaver6,
        BatterySaver7,
        BatterySaver8,
        SignalBars1,
        SignalBars2,
        SignalBars3,
        SignalBars4,
        SignalBars5,
        SignalNotConnected,
        Wifi1,
        Wifi2,
        Wifi3,
        MobSIMLock,
        MobSIMMissing,
        Vibrate,
        RoamingInternational,
        RoamingDomestic,
        CallForwardInternational,
        CallForwardRoaming,
        JpnRomanji,
        JpnRomanjiLock,
        JpnRomanjiShift,
        JpnRomanjiShiftLock,
        StatusDataTransfer,
        StatusDataTransferVPN,
        StatusDualSIM2,
        StatusDualSIM2VPN,
        StatusDualSIM1,
        StatusDualSIM1VPN,
        StatusSGLTE,
        StatusSGLTECell,
        StatusSGLTEDataVPN,
        StatusVPN,
        WifiHotspot,
        LanguageKor,
        LanguageCht,
        LanguageChs,
        USB,
        InkingToolFill,
        View,
        HighlightFill,
        Previous,
        Next,
        Clear,
        Sync,
        Download,
        Help,
        Upload,
        Emoji,
        TwoPage,
        LeaveChat,
        MailForward,
        RotateCamera,
        ClosePane,
        OpenPane,
        PreviewLink,
        AttachCamera,
        ZoomIn,
        Bookmarks,
        Document,
        ProtectedDocument,
        OpenInNewWindow,
        MailFill,
        ViewAll,
        VideoChat,
        Switch,
        Rename,
        Go,
        SurfaceHub,
        Remote,
        Click,
        Shuffle,
        Movies,
        SelectAll,
        Orientation,
        Import,
        ImportAll,
        Folder,
        Webcam,
        Picture,
        Caption,
        ChromeClose,
        ShowResults,
        Message,
        Leaf,
        CalendarDay,
        CalendarWeek,
        Characters,
        MailReplyAll,
        Read,
        ShowBcc,
        HideBcc,
        Cut,
        PaymentCard,
        Copy,
        Important,
        MailReply,
        Sort,
        MobileTablet,
        DisconnectDrive,
        MapDrive,
        ContactPresence,
        Priority,
        GotoToday,
        Font,
        FontColor,
        Contact2,
        FolderFill,
        Audio,
        Permissions,
        DisableUpdates,
        Unfavorite,
        OpenLocal,
        Italic,
        Underline,
        Bold,
        MoveToFolder,
        LikeDislike,
        Dislike,
        Like,
        AlignRight,
        AlignCenter,
        AlignLeft,
        OpenFile,
        ClearSelection,
        FontDecrease,
        FontIncrease,
        FontSize,
        CellPhone,
        Reshare,
        Tag,
        RepeatOne,
        RepeatAll,
        Calculator,
        Directions,
        Library,
        ChatBubbles,
        PostUpdate,
        NewFolder,
        CalendarReply,
        UnsyncFolder,
        SyncFolder,
        BlockContact,
        SwitchApps,
        AddFriend,
        Accept,
        GoToStart,
        BulletedList,
        Scan,
        Preview,
        Group,
        ZeroBars,
        OneBar,
        TwoBars,
        ThreeBars,
        FourBars,
        World,
        Comment,
        MusicInfo,
        DockLeft,
        DockRight,
        DockBottom,
        Repair,
        Accounts,
        DullSound,
        Manage,
        Street,
        Printer3D,
        RadioBullet,
        Stopwatch,
        Photo,
        ActionCenter,
        FullCircleMask,
        ChromeMinimize,
        ChromeMaximize,
        ChromeRestore,
        Annotation,
        BackSpaceQWERTYSm,
        BackSpaceQWERTYMd,
        Swipe,
        Fingerprint,
        Handwriting,
        ChromeBackToWindow,
        ChromeFullScreen,
        KeyboardStandard,
        KeyboardDismiss,
        Completed,
        ChromeAnnotate,
        Label,
        IBeam,
        IBeamOutline,
        FlickDown,
        FlickUp,
        FlickLeft,
        FlickRight,
        FeedbackApp,
        MusicAlbum,
        Streaming,
        Code,
        ReturnToWindow,
        LightningBolt,
        Info,
        CalculatorMultiply,
        CalculatorAddition,
        CalculatorSubtract,
        CalculatorDivide,
        CalculatorSquareroot,
        CalculatorPercentage,
        CalculatorNegate,
        CalculatorEqualTo,
        CalculatorBackspace,
        Component,
        DMC,
        Dock,
        MultimediaDMS,
        MultimediaDVR,
        MultimediaPMP,
        PrintfaxPrinterFile,
        Sensor,
        StorageOptical,
        Communications,
        Headset,
        Projector,
        Health,
        Wire,
        Webcam2,
        Input,
        Mouse,
        Smartcard,
        SmartcardVirtual,
        MediaStorageTower,
        ReturnKeySm,
        GameConsole,
        Network,
        StorageNetworkWireless,
        StorageTape,
        ChevronUpSmall,
        ChevronDownSmall,
        ChevronLeftSmall,
        ChevronRightSmall,
        ChevronUpMed,
        ChevronDownMed,
        ChevronLeftMed,
        ChevronRightMed,
        Devices2,
        ExpandTile,
        PC1,
        PresenceChicklet,
        PresenceChickletVideo,
        Reply,
        SetTile,
        Type,
        Korean,
        HalfAlpha,
        FullAlpha,
        Key12On,
        ChineseChangjie,
        QWERTYOn,
        QWERTYOff,
        ChineseQuick,
        Japanese,
        FullHiragana,
        FullKatakana,
        HalfKatakana,
        ChineseBoPoMoFo,
        ChinesePinyin,
        ConstructionCone,
        XboxOneConsole,
        Volume0,
        Volume1,
        Volume2,
        Volume3,
        BatteryUnknown,
        WifiAttentionOverlay,
        Robot,
        TapAndSend,
        FitPage,
        PasswordKeyShow,
        PasswordKeyHide,
        BidiLtr,
        BidiRtl,
        ForwardSm,
        CommaKey,
        DashKey,
        DullSoundKey,
        HalfDullSound,
        RightDoubleQuote,
        LeftDoubleQuote,
        PuncKeyRightBottom,
        PuncKey1,
        PuncKey2,
        PuncKey3,
        PuncKey4,
        PuncKey5,
        PuncKey6,
        PuncKey9,
        PuncKey7,
        PuncKey8,
        Frigid,
        Unknown,
        AreaChart,
        CheckList,
        Diagnostic,
        Equalizer,
        Process,
        Processing,
        ReportDocument,

        VideoSolid,
        MixedMediaBadge,
        DisconnectDisplay,
        Shield,
        Info2,
        ActionCenterAsterisk,
        Beta,
        SaveCopy,
        List,
        Asterisk,
        ErrorBadge,
        CircleRing,
        CircleFill,
        MergeCall,
        PrivateCall,
        Record2,
        AllAppsMirrored,
        BookmarksMirrored,
        BulletedListMirrored,
        CallForwardInternationalMirrored,
        CallForwardRoamingMirrored,
        ChromeBackMirrored,
        ClearSelectionMirrored,
        ClosePaneMirrored,
        ContactInfoMirrored,
        DockRightMirrored,
        DockLeftMirrored,
        ExpandTileMirrored,
        GoMirrored,
        GripperResizeMirrored,
        HelpMirrored,
        ImportMirrored,
        ImportAllMirrored,
        LeaveChatMirrored,
        ListMirrored,
        MailForwardMirrored,
        MailReplyMirrored,
        MailReplyAllMirrored,
        OpenPaneMirrored,
        OpenWithMirrored,
        ParkingLocationMirrored,
        ResizeMouseMediumMirrored,
        ResizeMouseSmallMirrored,
        ResizeMouseTallMirrored,
        ResizeTouchNarrowerMirrored,
        SendMirrored,
        SendFillMirrored,
        ShowResultsMirrored,
        Media,
        SyncError,
        Devices3,
        SlowMotionOn,
        Lightbulb,
        StatusCircle,
        StatusTriangle,
        StatusError,
        StatusWarning,
        Puzzle,
        CalendarSolid,
        HomeSolid,
        ParkingLocationSolid,
        ContactSolid,
        ConstructionSolid,
        AccidentSolid,
        Ringer,
        PDF,
        ThoughtBubble,
        HeartBroken,
        BatteryCharging10,
        BatterySaver9,
        BatterySaver10,
        CallForwardingMirrored,
        MultiSelectMirrored,
        Broom,
        ForwardCall,
        Trackers,
        Market,
        PieSingle,
        StockDown,
        StockUp,
        Design,
        Website,
        Drop,
        Radar,
        BusSolid,
        FerrySolid,
        StartPointSolid,
        StopPointSolid,
        EndPointSolid,
        AirplaneSolid,
        TrainSolid,
        WorkSolid,
        ReminderFill,
        Reminder,
        Heart,
        HeartFill,
        EthernetError,
        EthernetWarning,
        StatusConnecting1,
        StatusConnecting2,
        StatusUnsecure,
        WifiError0,
        WifiError1,
        WifiError2,
        WifiError3,
        WifiError4,
        WifiWarning0,
        WifiWarning1,
        WifiWarning2,
        WifiWarning3,
        WifiWarning4,
        Devices4,
        NUIIris,
        NUIFace,
        EditMirrored,
        NUIFPStartSlideHand,
        NUIFPStartSlideAction,
        NUIFPContinueSlideHand,
        NUIFPContinueSlideAction,
        NUIFPRollRightHand,
        NUIFPRollRightHandAction,
        NUIFPRollLeftHand,
        NUIFPRollLeftAction,
        NUIFPPressHand,
        NUIFPPressAction,
        NUIFPPressRepeatHand,
        NUIFPPressRepeatAction,
        StatusErrorFull,
        TaskViewExpanded,
        Certificate,
        BackSpaceQWERTYLg,
        ReturnKeyLg,
        FastForward,
        Rewind,
        Photo2,
        MobBattery0,
        MobBattery1,
        MobBattery2,
        MobBattery3,
        MobBattery4,
        MobBattery5,
        MobBattery6,
        MobBattery7,
        MobBattery8,
        MobBattery9,
        MobBattery10,
        MobBatteryCharging0,
        MobBatteryCharging1,
        MobBatteryCharging2,
        MobBatteryCharging3,
        MobBatteryCharging4,
        MobBatteryCharging5,
        MobBatteryCharging6,
        MobBatteryCharging7,
        MobBatteryCharging8,
        MobBatteryCharging9,
        MobBatteryCharging10,
        MobBatterySaver0,
        MobBatterySaver1,
        MobBatterySaver2,
        MobBatterySaver3,
        MobBatterySaver4,
        MobBatterySaver5,
        MobBatterySaver6,
        MobBatterySaver7,
        MobBatterySaver8,
        MobBatterySaver9,
        MobBatterySaver10,
        DictionaryCloud,
        ResetDrive,
        VolumeBars,
        Project,
        AdjustHologram,
        WifiCallBars,
        WifiCall0,
        WifiCall1,
        WifiCall2,
        WifiCall3,
        WifiCall4,
        Family,
        LockFeedback,
        DeviceDiscovery,
        WindDirection,
        RightArrowKeyTime0,
        Bug,
        TabletMode,
        StatusCircleLeft,
        StatusTriangleLeft,
        StatusErrorLeft,
        StatusWarningLeft,
        MobBatteryUnknown,
        NetworkTower,
        CityNext,
        CityNext2,
        Courthouse,
        Groceries,
        Sustainable,
        BuildingEnergy,
        ToggleFilled,
        ToggleBorder,
        SliderThumb,
        ToggleThumb,
        MiracastLogoSmall,
        MiracastLogoLarge,
        PLAP,
        Badge,
        SignalRoaming,
        MobileLocked,
        InsiderHubApp,
        PersonalFolder,
        HomeGroup,
        MyNetwork,
        KeyboardFull,
        Cafe,
        MobSignal1,
        MobSignal2,
        MobSignal3,
        MobSignal4,
        MobSignal5,
        MobWifi1,
        MobWifi2,
        MobWifi3,
        MobWifi4,
        MobAirplane,
        MobBluetooth,
        MobActionCenter,
        MobLocation,
        MobWifiHotspot,
        LanguageJpn,
        MobQuietHours,
        MobDrivingMode,
        SpeedOff,
        SpeedMedium,
        SpeedHigh,
        ThisPC,
        MusicNote,
        FileExplorer,
        FileExplorerApp,
        LeftArrowKeyTime0,
        MicOff,
        MicSleep,
        MicError,
        PlaybackRate1x,
        PlaybackRateOther,
        CashDrawer,
        BarcodeScanner,
        ReceiptPrinter,
        MagStripeReader,
        CompletedSolid,
        CompanionApp,
        Favicon2,
        SwipeRevealArt,
        MicOn,
        MicClipping,
        TabletSelected,
        MobileSelected,
        LaptopSelected,
        TVMonitorSelected,
        DeveloperTools,
        MobCallForwarding,
        MobCallForwardingMirrored,
        BodyCam,
        PoliceCar,
        Draw,
        DrawSolid,
        LowerBrightness,
        ScrollUpDown,
        DateTime,
        Tiles,
        PartyLeader,
        AppIconDefault,
        Calories,
        BandBattery0,
        BandBattery1,
        BandBattery2,
        BandBattery3,
        BandBattery4,
        BandBattery5,
        BandBattery6,
        AddSurfaceHub,
        DevUpdate,
        Unit,
        AddTo,
        RemoveFrom,
        RadioBtnOff,
        RadioBtnOn,
        RadioBullet2,
        ExploreContent,
        Blocked2,
        ScrollMode,
        ZoomMode,
        PanMode,
        WiredUSB,
        WirelessUSB,
        USBSafeConnect,

        ActionCenterNotificationMirrored,
        ActionCenterMirrored,
        SubscriptionAdd,
        ResetDevice,
        SubscriptionAddMirrored,
        QRCode,
        Feedback,
        Subtitles,
        SubtitlesAudio,
        OpenFolderHorizontal,
        CalendarMirrored,
        MobeSIM,
        MobeSIMNoProfile,
        MobeSIMLocked,
        MobeSIMBusy,
        SignalError,
        StreamingEnterprise,
        Headphone0,
        Headphone1,
        Headphone2,
        Headphone3,
        Apps,
        KeyboardBrightness,
        KeyboardLowerBrightness,
        SkipBack10,
        SkipForward30,
        TreeFolderFolder,
        TreeFolderFolderFill,
        TreeFolderFolderOpen,
        TreeFolderFolderOpenFill,
        MultimediaDMP,
        KeyboardOneHanded,
        Narrator,
        EmojiTabPeople,
        EmojiTabSmilesAnimals,
        EmojiTabCelebrationObjects,
        EmojiTabFoodPlants,
        EmojiTabTransitPlaces,
        EmojiTabSymbols,
        EmojiTabTextSmiles,
        EmojiTabFavorites,
        EmojiSwatch,
        ConnectApp,
        CompanionDeviceFramework,
        Ruler,
        FingerInking,
        StrokeErase,
        PointErase,
        ClearAllInk,
        Pencil,
        Marker,
        InkingCaret,
        InkingColorOutline,
        InkingColorFill,
        HardDrive,
        NetworkAdapter,
        Touchscreen,
        NetworkPrinter,
        CloudPrinter,
        KeyboardShortcut,
        BrushSize,
        NarratorForward,
        NarratorForwardMirrored,
        SyncBadge12,
        RingerBadge12,
        AsteriskBadge12,
        ErrorBadge12,
        CircleRingBadge12,
        CircleFillBadge12,
        ImportantBadge12,
        MailBadge12,
        PauseBadge12,
        PlayBadge12,
        PenWorkspace,
        CaretRight8,
        CaretLeftSolid8,
        CaretRightSolid8,
        CaretUpSolid8,
        CaretDownSolid8,
        Strikethrough,
        Export,
        ExportMirrored,
        ButtonMenu,
        CloudSearch,
        PinyinIMELogo,
        CalligraphyPen,
        ReplyMirrored,
        LockscreenDesktop,
        TaskViewSettings,
        MiniExpand2Mirrored,
        MiniContract2Mirrored,
        Play36,
        PenPalette,
        GuestUser,
        SettingsBattery,
        TaskbarPhone,
        LockScreenGlance,
        GenericScan,
        ImageExport,
        WifiEthernet,
        ActionCenterQuiet,
        ActionCenterQuietNotification,
        TrackersMirrored,
        DateTimeMirrored,
        Wheel,
        VirtualMachineGroup,
        ButtonView2,
        PenWorkspaceMirrored,
        PenPaletteMirrored,
        StrokeEraseMirrored,
        PointEraseMirrored,
        ClearAllInkMirrored,
        BackgroundToggle,
        Marquee,
        ChromeCloseContrast,
        ChromeMinimizeContrast,
        ChromeMaximizeContrast,
        ChromeRestoreContrast,
        TrafficLight,
        Replay,
        Eyedropper,
        LineDisplay,
        PINPad,
        SignatureCapture,
        ChipCardCreditCardReader,
        PlayerSettings,
        LandscapeOrientation,
        Flow,
        Touchpad,
        Speech,

        KnowledgeArticle,
        Relationship,
        DefaultAPN,
        UserAPN,
        DoublePinyin,
        BlueLight,
        ButtonA,
        ButtonB,
        ButtonY,
        ButtonX,
        ArrowUp8,
        ArrowDown8,
        ArrowRight8,
        ArrowLeft8,
        QuarentinedItems,
        QuarentinedItemsMirrored,
        Protractor,
        ChecklistMirrored,
        StatusCircle7,
        StatusCheckmark7,
        StatusErrorCircle7,
        Connected,
        PencilFill,
        CalligraphyFill,
        QuarterStarLeft,
        QuarterStarRight,
        ThreeQuarterStarLeft,
        ThreeQuarterStarRight,
        QuietHoursBadge12,
        BackMirrored,
        ForwardMirrored,
        ChromeBackContrast,
        ChromeBackContrastMirrored,
        ChromeBackToWindowContrast,
        ChromeFullScreenContrast,
        GridView,
        ClipboardList,
        ClipboardListMirrored,
        OutlineQuarterStarLeft,
        OutlineQuarterStarRight,
        OutlineHalfStarLeft,
        OutlineHalfStarRight,
        OutlineThreeQuarterStarLeft,
        OutlineThreeQuarterStarRight,
        SpatialVolume0,
        SpatialVolume1,
        SpatialVolume2,
        SpatialVolume3,
        ApplicationGuard,
        OutlineStarLeftHalf,
        OutlineStarRightHalf,
        ChromeAnnotateContrast,
        DefenderBadge12,
        DetachablePC,
        LeftStick,
        RightStick,
        TriggerLeft,
        TriggerRight,
        BumperLeft,
        BumperRight,
        Dpad,
        EnglishPunctuation,
        ChinesePunctuation,
        HMD,
        CtrlSpatialRight,
        PaginationDotOutline10,
        PaginationDotSolid10,
        StrokeErase2,
        SmallErase,
        LargeErase,
        FolderHorizontal,
        MicrophoneListening,
        StatusExclamationCircle7,
        Video360,
        GiftboxOpen,
        StatusCircleOuter,
        StatusCircleInner,
        StatusCircleRing,
        StatusTriangleOuter,
        StatusTriangleInner,
        StatusTriangleExclamation,
        StatusCircleExclamation,
        StatusCircleErrorX,
        StatusCircleCheckmark,
        StatusCircleInfo,
        StatusCircleBlock,
        StatusCircleBlock2,
        StatusCircleQuestionMark,
        StatusCircleSync,
        Dial1,
        Dial2,
        Dial3,
        Dial4,
        Dial5,
        Dial6,
        Dial7,
        Dial8,
        Dial9,
        Dial10,
        Dial11,
        Dial12,
        Dial13,
        Dial14,
        Dial15,
        Dial16,
        DialShape1,
        DialShape2,
        DialShape3,
        DialShape4,
        TollSolid,
        TrafficCongestionSolid,
        ExploreContentSingle,
        CollapseContent,
        CollapseContentSingle,
        InfoSolid,
        GroupList,
        CaretBottomRightSolidCenter8,
        ProgressRingDots,
        Checkbox14,
        CheckboxComposite14,
        CheckboxIndeterminateCombo14,
        CheckboxIndeterminateCombo,
        StatusPause7,
        CharacterAppearance,
        Lexicon,
        ScreenTime,
        HeadlessDevice,
        NetworkSharing,
        EyeGaze,
        ToggleLeft,
        ToggleRight,
        WindowsInsider,
        ChromeSwitch,
        ChromeSwitchContast,
        StatusCheckmark,
        StatusCheckmarkLeft,
        KeyboardLeftAligned,
        KeyboardRightAligned,
        KeyboardSettings,
        NetworkPhysical,
        IOT,
        UnknownMirrored,
        ViewDashboard,
        ExploitProtectionSettings,
        KeyboardNarrow,
        Keyboard12Key,
        KeyboardDock,
        KeyboardUndock,
        KeyboardLeftDock,
        KeyboardRightDock,
        Ear,
        PointerHand,
        Bullseye,
        LocaleLanguage,

        PassiveAuthentication,
        ColorSolid,
        NetworkOffline,
        NetworkConnected,
        NetworkConnectedCheckmark,
        SignOut,
        StatusInfo,
        StatusInfoLeft,
        NearbySharing,
        CtrlSpatialLeft,
        InteractiveDashboard,
        ClippingTool,
        RectangularClipping,
        FreeFormClipping,
        CopyTo,
        DynamicLock,
        PenTips,
        PenTipsMirrored,
        HWPJoin,
        HWPInsert,
        HWPStrikeThrough,
        HWPScratchOut,
        HWPSplit,
        HWPNewLine,
        HWPOverwrite,
        MobWifiWarning1,
        MobWifiWarning2,
        MobWifiWarning3,
        MobWifiWarning4,
        Globe2,
        SpecialEffectSize,
        GIF,
        Sticker2,
        SurfaceHubSelected,
        HoloLensSelected,
        Earbud,
        MixVolumes,
        Safe,
        LaptopSecure,
        PrintDefault,
        PageMirrored,
        LandscapeOrientationMirrored,
        ColorOff,
        PrintAllPages,
        PrintCustomRange,
        PageMarginPortraitNarrow,
        PageMarginPortraitNormal,
        PageMarginPortraitModerate,
        PageMarginPortraitWide,
        PageMarginLandscapeNarrow,
        PageMarginLandscapeNormal,
        PageMarginLandscapeModerate,
        PageMarginLandscapeWide,
        CollateLandscape,
        CollatePortrait,
        CollatePortraitSeparated,
        DuplexLandscapeOneSided,
        DuplexLandscapeOneSidedMirrored,
        DuplexLandscapeTwoSidedLongEdge,
        DuplexLandscapeTwoSidedLongEdgeMirrored,
        DuplexLandscapeTwoSidedShortEdge,
        DuplexLandscapeTwoSidedShortEdgeMirrored,
        DuplexPortraitOneSided,
        DuplexPortraitOneSidedMirrored,
        DuplexPortraitTwoSidedLongEdge,
        DuplexPortraitTwoSidedLongEdgeMirrored,
        DuplexPortraitTwoSidedShortEdge,
        DuplexPortraitTwoSidedShortEdgeMirrored,
        PPSOneLandscape,
        PPSTwoLandscape,
        PPSTwoPortrait,
        PPSFourLandscape,
        PPSFourPortrait,
        HolePunchOff,
        HolePunchPortraitLeft,
        HolePunchPortraitRight,
        HolePunchPortraitTop,
        HolePunchPortraitBottom,
        HolePunchLandscapeLeft,
        HolePunchLandscapeRight,
        HolePunchLandscapeTop,
        HolePunchLandscapeBottom,
        StaplingOff,
        StaplingPortraitTopLeft,
        StaplingPortraitTopRight,
        StaplingPortraitBottomRight,
        StaplingPortraitTwoLeft,
        StaplingPortraitTwoRight,
        StaplingPortraitTwoTop,
        StaplingPortraitTwoBottom,
        StaplingPortraitBookBinding,
        StaplingLandscapeTopLeft,
        StaplingLandscapeTopRight,
        StaplingLandscapeBottomLeft,
        StaplingLandscapeBottomRight,
        StaplingLandscapeTwoLeft,
        StaplingLandscapeTwoRight,
        StaplingLandscapeTwoTop,
        StaplingLandscapeTwoBottom,
        StaplingLandscapeBookBinding,
        StatusDataTransferRoaming,
        MobSIMError,
        CollateLandscapeSeparated,
        PPSOnePortrait,
        StaplingPortraitBottomLeft,
        PlaySolid,
        RepeatOff,
        Set,
        SetSolid,
        FuzzyReading,
        VerticalBattery0,
        VerticalBattery1,
        VerticalBattery2,
        VerticalBattery3,
        VerticalBattery4,
        VerticalBattery5,
        VerticalBattery6,
        VerticalBattery7,
        VerticalBattery8,
        VerticalBattery9,
        VerticalBattery10,
        VerticalBatteryCharging0,
        VerticalBatteryCharging1,
        VerticalBatteryCharging2,

        VerticalBatteryCharging3,
        VerticalBatteryCharging4,
        VerticalBatteryCharging5,
        VerticalBatteryCharging6,
        VerticalBatteryCharging7,
        VerticalBatteryCharging8,
        VerticalBatteryCharging9,
        VerticalBatteryCharging10,
        VerticalBatteryUnknown,
        DoublePortrait,
        DoubleLandscape,
        SinglePortrait,
        SingleLandscape,
        SIMError,
        SIMMissing,
        SIMLock,
        eSIM,
        eSIMNoProfile,
        eSIMLocked,
        eSIMBusy,
        NoiseCancelation,
        NoiseCancelationOff,
        MusicSharing,
        MusicSharingOff,
        CircleShapeSolid,
        CHTLanguageBar,
        ComposeMode,
        ExpressiveInputEntry,
        EmojiTabMoreSymbols,
        WebSearch,
        Kiosk,
        RTTLogo,
        VoiceCall,
        GoToMessage,
        ReturnToCall,
        StartPresenting,
        StopPresenting,
        ProductivityMode,
        SetHistoryStatus,
        SetHistoryStatus2,
        Keyboardsettings20,
        OneHandedRight20,
        OneHandedLeft20,
        Split20,
        Full20,
        Handwriting20,
        CheveronLeft20,
        CheveronLeft32,
        CheveronRight20,
        CheveronRight32,
        MicOff2,
        DeliveryOptimization,
        CancelMedium,
        SearchMedium,
        AcceptMedium,
        RevealPasswordMedium,
        DeleteWord,
        DeleteWordFill,
        DeleteLines,
        DeleteLinesFill,
        InstertWords,
        InstertWordsFill,
        JoinWords,
        JoinWordsFill,
        OverwriteWords,
        OverwriteWordsFill,
        AddNewLine,
        AddNewLineFill,
        OverwriteWordsKorean,
        OverwriteWordsFillKorean,
        EducationIcon,
        WindowSnipping,
        VideoCapture,
        StatusSecured,
        NarratorApp,
        PowerButtonUpdate,
        RestartUpdate,
        UpdateStatusDot,
        Eject,
        Spelling,
        SpellingKorean,
        SpellingSerbian,
        SpellingChinese,
        FolderSelect,
        SmartScreen,
        ExploitProtection,
        AddBold,
        SubtractBold,
        BackSolidBold,
        ForwardSolidBold,
        PauseBold,
        ClickSolid,
        SettingsSolid,
        MicrophoneSolidBold,
        SpeechSolidBold,
        ClickedOutLoudSolidBold
    }
}
